[build]
  command = "npm install --force && npm run build:netlify"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "18.17.1"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_VERSION = "9.6.7"
  YARN_VERSION = "1.22.19"
  YARN_FLAGS = "--ignore-engines"

# Configurações de redirecionamento SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Redirecionamentos personalizados
[[redirects]]
  from = "/blog/:year/:month/:slug"
  to = "/blog/:slug"
  status = 301

# Configurações de cabeçalhos de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://unpkg.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com data:; connect-src 'self' https://api.colegionarfive.ao;"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    
# Cache otimizado para assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Configurações de ambiente
[context.production.environment]
  NODE_ENV = "production"
  VITE_API_URL = "https://api.colegionarfive.ao"
  VITE_GA_TRACKING_ID = ""
  VITE_SENTRY_DSN = ""

[context.deploy-preview.environment]
  NODE_ENV = "staging"
  VITE_API_URL = "https://staging-api.colegionarfive.ao"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  VITE_API_URL = "https://dev-api.colegionarfive.ao"

# Configurações de build
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

# Configurações de funções do Netlify
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "@prisma/adapter-pg"]

# Configurações de deploy
[dev]
  framework = "vite"
  command = "npm run dev"
  targetPort = 3000
  publish = "dist"
  autoLaunch = true
